### PR TITLE
Sprint

### PR DESCRIPTION
**Pull request by NoxPardalis**

### CODE REVIEW

**Comment by SytseOegema** [comment]
Thanks,

Regarding the 'hallo' function, commented code, unappropraite logging statements and the general reformatting. I'll make sure that is done by tomorrow night.

Regarding the other points:

- Do you have an example of statements that don't terminate?
- Is the ip + port check a requirement for now or can we do this for the next sprint?
- Testing is something we will look into this sprint as well.

**Comment by SytseOegema** [comment]
We improved comments, log statements and formatting.
I also added a Regex to check the validity of the ip+port when adding a new server. I did look into pinging a server, but JavaScript does not provide a standard function for this. We could work around this, but that is not going to be finished by tonight.

**Comment by Feikoritsema** [comment]
Alright, thanks for the changes. I will merge it, but do stay focused on the clean code for the next sprint. Also, you might wanna look into validating a server better for next sprint indeed, as this would be some good functionality to have.

**Comment by Feikoritsema** [comment]
Oh and besides that, please make sure travis builds work for the last sprint, shouldn't be too much of an issue.

**Pull request merged**
